USE BokhandelDB;

GO

CREATE TABLE Författare (
    ID INT PRIMARY KEY IDENTITY(1,1),
    Förnamn NVARCHAR(50) NOT NULL,
    Efternamn NVARCHAR(50) NOT NULL,
    Födelsedatum DATE NOT NULL
);

GO

CREATE TABLE Förlag (
    FörlagID INT PRIMARY KEY IDENTITY(1,1),
    Namn NVARCHAR(50) NOT NULL
);

GO

CREATE TABLE Butiker (
    ButikID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    Namn NVARCHAR(50) NOT NULL,
    Stad NVARCHAR(50) NOT NULL,
    Adress NVARCHAR(100) NOT NULL
);

GO

CREATE TABLE Kunder (
    KundID INT PRIMARY KEY IDENTITY(1,1),
    Förnamn NVARCHAR(50) NOT NULL,
    Efternamn NVARCHAR(50) NOT NULL,
    Email NVARCHAR(255) NOT NULL UNIQUE
);

GO

CREATE TABLE Kategorier (
    KategoriID INT PRIMARY KEY IDENTITY(1,1),
    Namn NVARCHAR(50) NOT NULL UNIQUE
);

GO

CREATE TABLE Böcker (
    ISBN13 CHAR(13) PRIMARY KEY,
    Titel NVARCHAR(200) NOT NULL,
    Pris DECIMAL(10,2) NOT NULL CHECK(Pris >= 0),
    Språk CHAR(2) NOT NULL,
    Utgivningsdatum DATE NOT NULL,
    FörlagID INT NOT NULL REFERENCES Förlag(FörlagID)
);

GO

CREATE TABLE Ordrar (
    OrderID INT PRIMARY KEY IDENTITY(1,1),
    KundID INT NOT NULL REFERENCES Kunder(KundID),
    OrderDatum DATETIME2 NOT NULL DEFAULT SYSDATETIME()
);

GO

CREATE TABLE BokFörfattare (
    ISBN13 CHAR(13) NOT NULL REFERENCES Böcker(ISBN13),
    FörfattareID INT NOT NULL REFERENCES Författare(ID),
    PRIMARY KEY(ISBN13, FörfattareID)
);

GO

CREATE TABLE LagerSaldo (
    ButikID INT NOT NULL REFERENCES Butiker(ButikID),
    ISBN13 CHAR(13) NOT NULL REFERENCES Böcker(ISBN13),
    Antal INT NOT NULL CHECK(Antal > 0),
    PRIMARY KEY(ButikID, ISBN13)
);

GO

CREATE TABLE OrderRader (
    OrderId INT NOT NULL REFERENCES Ordrar(OrderID),
    ISBN13 CHAR(13) NOT NULL REFERENCES Böcker(ISBN13),
    Antal INT NOT NULL CHECK(Antal >= 0),
    Pris DECIMAL(10,2) NOT NULL CHECK(Pris >= 0),
    PRIMARY KEY(OrderID, ISBN13)  
);

GO

CREATE TABLE BokKategori (
    ISBN13 CHAR(13) NOT NULL REFERENCES Böcker(ISBN13),
    KategoriID INT NOT NULL REFERENCES Kategorier(KategoriID),
    PRIMARY KEY(ISBN13, KategoriID)      
);